### ISSUE TITLE
Remove ui5.yaml and manifest.json due to official schemas availalbe

### ISSUE THREAD

**Issue by gregorwolf** [Soontao/sap-json-schemas#5]
Hi @Soontao,

I've installed and activated your extenstion in VS Code I get this false positive for a manifest.json:

![Screenshot 2022-08-27 at 10 36 41](https://user-images.githubusercontent.com/2639535/187022425-1e6cba05-be92-4658-96c8-25ac4c922feb.png)

I would suggest that you remove ui5.yaml and manifest.json as there are SAP maintained schemas available now:

- https://raw.githubusercontent.com/SAP/ui5-manifest/master/schema.json
- https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

Best Regards
Gregor

**Comment by Soontao** [comment]
Hi @gregorwolf 

sorry I find this issue just now!

yes, let me have a look at the schemas.

thanks

**Comment by Soontao** [comment]
release a new version 0.1.9, and change the json schema link to the SAP official one. will check other artifacts later. 

Thanks.
